version: '3'
services:
  database:
    build:
      context: ..
      dockerfile: build/mysql.dockerfile
      network: host
    env_file:
      blog_service.env
    container_name: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: source ./configs/mysql_env.sh;mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD
      interval: 10s
      retries: 6
      start_period: 10s

  blog_service:
    build:
      context: ..
      dockerfile: build/blog_service.dockerfile
    volumes:
      - ..:/home # Use for debugging
    env_file:
      blog_service.env
    depends_on:
      - database
    container_name: blog_service

  blog_initialization:
    build:
      context: ..
      dockerfile: build/blog_initialization.dockerfile
    volumes:
      - ..:/home # Use for debugging
    env_file:
      blog_service.env
    depends_on:
      - database
    container_name: blog_initialization
