[template]
src = "blog_service.yml.toml"
dest = "configs/blog_service.yml"
keys = [
    "/blog/database/type",
    "/blog/database/url",
    "/blog/database/username",
    "/blog/database/password",
    "/blog/database/dbname",
]
